name: Manual Issue Creator

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the issue'
        default: 'New Issue'
        required: true
        type: string
      body:
        description: 'Description of the issue'
        default: 'This is a new issue created via a GitHub Actions workflow.'
        required: false
        type: string

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create \
          --title "${{ inputs.title }}" \
          --body "${{ inputs.body }}"
