

name: Manual Issue Creator

on:
  workflow_dispatch: # Trigger workflow manually
 
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install --upgrade pip # Add additional libraries if needed

    - name: Run Python script
      env:
        IMAP_SERVER: "imap.gmail.com"
        EMAIL_ACCOUNT: ${{ secrets.EMAIL_ACCOUNT }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        REPO: "your-username/your-repo"
      run: python fetch_emails_and_create_issues.py

